version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
    tty: true
    stdin_open: true
  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
  selenium_chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
volumes:
  db:
  bundle:
  node_modules:
